### ISSUE TITLE
ssh: Could not resolve hostname invalid: Name or service not known

### ISSUE THREAD

**Issue by tobit6795** [jasongerard/remoteit-cli#1]
first of all, thank you very much for this amazing work.
The cli worked until now. i tried it on two different machines with this command:
 ssh -D 8080 pi@$(remoteit connect ssh-testipi 127.0.0.1 --format ssh). it already worked yesterday but now i got "could not resolve hostname". im able to login and to list devices.

**Comment by jasongerard** [comment]
@tobit6795 What is the output of just running `remoteit connect ssh-testipi 127.0.0.1 --format ssh` ?

It would seem that the remote.it API is sometimes returning a value that is unexpected and my code doesn't account for that properly. The first time I ran your command I got a panic, the second time it worked fine. Looking at were the panic happens, it's in the parsing of the proxy value for ssh. I will add some better logging to record the output that is received to help diagnose the issue better.

For now all I can say is, try again.

**Comment by jasongerard** [comment]
@tobit6795 I have added a `--loghttp` flag that will log all HTTP request/response operations to ~/.remoteit/http.log. It removes the Authorization, DeverloperKey, and Token headers before logging. If you continue to have the issue please try with that flag on. Feel free to send me the logs to check it out. It does not filter out the IP addresses in the result so you must remove that yourself if it's sensitive.

**Comment by tobit6795** [comment]
okay thanks, l'll try again the next days

**Comment by tobit6795** [comment]
what is the easy way to update the version? my version does not have the --http-log flag

**Comment by tobit6795** [comment]
```
ssh root@$(remoteit connect SSH-Droid 127.0.0.1 --format ssh)
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/jasongerard/remoteit-cli/cmd.glob..func1(0x6d0a98, 0x184f3a0, 0x2, 0x4)
	/home/kem/go/remoteit-cli/cmd/connect.go:136 +0xaa0
github.com/spf13/cobra.(*Command).execute(0x6d0a98, 0x184f300, 0x4, 0x4, 0x6d0a98, 0x184f300)
	/home/kem/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x20c
github.com/spf13/cobra.(*Command).ExecuteC(0x6d0968, 0x18160f0, 0x0, 0x6d0cf8)
	/home/kem/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x210
github.com/spf13/cobra.(*Command).Execute(0x6d0968, 0x3d674, 0x33f64c)
	/home/kem/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x1c
github.com/jasongerard/remoteit-cli/cmd.Execute()
	/home/kem/go/remoteit-cli/cmd/root.go:53 +0x20
main.main()
	/home/kem/go/remoteit-cli/main.go:6 +0x14
ssh: Could not resolve hostname : Name or service not known
```

this is what im getting now. Im able to login and list devices
